#!/usr/bin/env node

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

import { register as registerListContainers } from "./tools/listContainers.js";
import { register as registerInspectContainer } from "./tools/inspectContainer.js";
import { register as registerContainerLogs } from "./tools/containerLogs.js";
import { register as registerListImages } from "./tools/listImages.js";
import { register as registerInspectImage } from "./tools/inspectImage.js";
import { register as registerListVolumes } from "./tools/listVolumes.js";
import { register as registerListNetworks } from "./tools/listNetworks.js";
import { register as registerSystemInfo } from "./tools/systemInfo.js";
import { register as registerDiskUsage } from "./tools/diskUsage.js";
import { register as registerSearchHub } from "./tools/searchHub.js";
import { register as registerRun } from "./tools/run.js";
import { register as registerCreate } from "./tools/create.js";
import { register as registerStart } from "./tools/start.js";
import { register as registerStop } from "./tools/stop.js";
import { register as registerRestart } from "./tools/restart.js";
import { register as registerKill } from "./tools/kill.js";
import { register as registerRm } from "./tools/rm.js";
import { register as registerPause } from "./tools/pause.js";
import { register as registerUnpause } from "./tools/unpause.js";
import { register as registerExec } from "./tools/exec.js";
import { register as registerPull } from "./tools/pull.js";
import { register as registerPush } from "./tools/push.js";
import { register as registerBuild } from "./tools/build.js";
import { register as registerTag } from "./tools/tag.js";
import { register as registerRmi } from "./tools/rmi.js";
import { register as registerCommit } from "./tools/commit.js";
import { register as registerSave } from "./tools/save.js";
import { register as registerLoad } from "./tools/load.js";
import { register as registerComposeUp } from "./tools/composeUp.js";
import { register as registerComposeDown } from "./tools/composeDown.js";
import { register as registerComposePs } from "./tools/composePs.js";
import { register as registerComposeLogs } from "./tools/composeLogs.js";
import { register as registerComposeBuild } from "./tools/composeBuild.js";
import { register as registerComposeRestart } from "./tools/composeRestart.js";
import { register as registerComposePull } from "./tools/composePull.js";
import { register as registerComposeExec } from "./tools/composeExec.js";
import { register as registerVolumeCreate } from "./tools/volumeCreate.js";
import { register as registerVolumeRm } from "./tools/volumeRm.js";
import { register as registerVolumeInspect } from "./tools/volumeInspect.js";
import { register as registerVolumePrune } from "./tools/volumePrune.js";
import { register as registerNetworkCreate } from "./tools/networkCreate.js";
import { register as registerNetworkRm } from "./tools/networkRm.js";
import { register as registerNetworkConnect } from "./tools/networkConnect.js";
import { register as registerNetworkDisconnect } from "./tools/networkDisconnect.js";
import { register as registerNetworkInspect } from "./tools/networkInspect.js";
import { register as registerNetworkPrune } from "./tools/networkPrune.js";
import { register as registerSystemPrune } from "./tools/systemPrune.js";
import { register as registerContainerPrune } from "./tools/containerPrune.js";
import { register as registerImagePrune } from "./tools/imagePrune.js";
import { register as registerCp } from "./tools/cp.js";
import { register as registerStats } from "./tools/stats.js";
import { register as registerTop } from "./tools/top.js";
import { register as registerEvents } from "./tools/events.js";
import { register as registerUpdate } from "./tools/update.js";
import { register as registerWait } from "./tools/wait.js";
import { register as registerBuildxBuild } from "./tools/buildxBuild.js";
import { register as registerBuildxLs } from "./tools/buildxLs.js";
import { register as registerBuildxCreate } from "./tools/buildxCreate.js";
import { register as registerBuildxRm } from "./tools/buildxRm.js";
import { register as registerBuildxInspect } from "./tools/buildxInspect.js";
import { register as registerBuildxUse } from "./tools/buildxUse.js";
import { register as registerBuildxImagetools } from "./tools/buildxImagetools.js";
import { register as registerBuilderPrune } from "./tools/builderPrune.js";
import { register as registerManifestCreate } from "./tools/manifestCreate.js";
import { register as registerManifestInspect } from "./tools/manifestInspect.js";
import { register as registerManifestAnnotate } from "./tools/manifestAnnotate.js";
import { register as registerManifestPush } from "./tools/manifestPush.js";
import { register as registerManifestRm } from "./tools/manifestRm.js";
import { register as registerComposeConfig } from "./tools/composeConfig.js";
import { register as registerComposeCp } from "./tools/composeCp.js";
import { register as registerComposeCreate } from "./tools/composeCreate.js";
import { register as registerComposeEvents } from "./tools/composeEvents.js";
import { register as registerComposeImages } from "./tools/composeImages.js";
import { register as registerComposeKill } from "./tools/composeKill.js";
import { register as registerComposeLs } from "./tools/composeLs.js";
import { register as registerComposePause } from "./tools/composePause.js";
import { register as registerComposeUnpause } from "./tools/composeUnpause.js";
import { register as registerComposePort } from "./tools/composePort.js";
import { register as registerComposeRm } from "./tools/composeRm.js";
import { register as registerComposeRun } from "./tools/composeRun.js";
import { register as registerComposeScale } from "./tools/composeScale.js";
import { register as registerComposeStart } from "./tools/composeStart.js";
import { register as registerComposeStop } from "./tools/composeStop.js";
import { register as registerComposeTop } from "./tools/composeTop.js";
import { register as registerDiff } from "./tools/diff.js";
import { register as registerExport } from "./tools/export.js";
import { register as registerPort } from "./tools/port.js";
import { register as registerRename } from "./tools/rename.js";
import { register as registerImageHistory } from "./tools/imageHistory.js";
import { register as registerImport } from "./tools/import.js";
import { register as registerContextCreate } from "./tools/contextCreate.js";
import { register as registerContextLs } from "./tools/contextLs.js";
import { register as registerContextInspect } from "./tools/contextInspect.js";
import { register as registerContextRm } from "./tools/contextRm.js";
import { register as registerContextUse } from "./tools/contextUse.js";
import { register as registerContextShow } from "./tools/contextShow.js";
import { register as registerLogin } from "./tools/login.js";
import { register as registerLogout } from "./tools/logout.js";
import { register as registerSwarmInit } from "./tools/swarmInit.js";
import { register as registerSwarmJoin } from "./tools/swarmJoin.js";
import { register as registerSwarmLeave } from "./tools/swarmLeave.js";
import { register as registerSwarmJoinToken } from "./tools/swarmJoinToken.js";
import { register as registerSwarmUpdate } from "./tools/swarmUpdate.js";
import { register as registerSwarmUnlock } from "./tools/swarmUnlock.js";
import { register as registerSwarmUnlockKey } from "./tools/swarmUnlockKey.js";
import { register as registerSwarmCa } from "./tools/swarmCa.js";
import { register as registerServiceCreate } from "./tools/serviceCreate.js";
import { register as registerServiceUpdate } from "./tools/serviceUpdate.js";
import { register as registerServiceRm } from "./tools/serviceRm.js";
import { register as registerServiceLs } from "./tools/serviceLs.js";
import { register as registerServiceInspect } from "./tools/serviceInspect.js";
import { register as registerServiceLogs } from "./tools/serviceLogs.js";
import { register as registerServicePs } from "./tools/servicePs.js";
import { register as registerServiceScale } from "./tools/serviceScale.js";
import { register as registerServiceRollback } from "./tools/serviceRollback.js";
import { register as registerNodeLs } from "./tools/nodeLs.js";
import { register as registerNodeInspect } from "./tools/nodeInspect.js";
import { register as registerNodePs } from "./tools/nodePs.js";
import { register as registerNodeRm } from "./tools/nodeRm.js";
import { register as registerNodeUpdate } from "./tools/nodeUpdate.js";
import { register as registerNodePromote } from "./tools/nodePromote.js";
import { register as registerNodeDemote } from "./tools/nodeDemote.js";
import { register as registerStackDeploy } from "./tools/stackDeploy.js";
import { register as registerStackRm } from "./tools/stackRm.js";
import { register as registerStackLs } from "./tools/stackLs.js";
import { register as registerStackPs } from "./tools/stackPs.js";
import { register as registerStackServices } from "./tools/stackServices.js";
import { register as registerStackConfig } from "./tools/stackConfig.js";
import { register as registerConfigCreate } from "./tools/configCreate.js";
import { register as registerConfigInspect } from "./tools/configInspect.js";
import { register as registerConfigLs } from "./tools/configLs.js";
import { register as registerConfigRm } from "./tools/configRm.js";
import { register as registerSecretCreate } from "./tools/secretCreate.js";
import { register as registerSecretInspect } from "./tools/secretInspect.js";
import { register as registerSecretLs } from "./tools/secretLs.js";
import { register as registerSecretRm } from "./tools/secretRm.js";
import { register as registerTrustInspect } from "./tools/trustInspect.js";
import { register as registerTrustSign } from "./tools/trustSign.js";
import { register as registerTrustRevoke } from "./tools/trustRevoke.js";
import { register as registerTrustKey } from "./tools/trustKey.js";
import { register as registerVersion } from "./tools/version.js";
import { register as registerComposeVersion } from "./tools/composeVersion.js";
import { register as registerComposeWatch } from "./tools/composeWatch.js";
import { register as registerScoutQuickview } from "./tools/scoutQuickview.js";
import { register as registerScoutCves } from "./tools/scoutCves.js";
import { register as registerScoutRecommendations } from "./tools/scoutRecommendations.js";
import { register as registerPluginLs } from "./tools/pluginLs.js";
import { register as registerPluginInstall } from "./tools/pluginInstall.js";
import { register as registerPluginRm } from "./tools/pluginRm.js";
import { register as registerPluginEnable } from "./tools/pluginEnable.js";

const server = new McpServer({
  name: "docker-mcp",
  version: "1.0.0",
});

registerListContainers(server);
registerInspectContainer(server);
registerContainerLogs(server);
registerListImages(server);
registerInspectImage(server);
registerListVolumes(server);
registerListNetworks(server);
registerSystemInfo(server);
registerDiskUsage(server);
registerSearchHub(server);
registerRun(server);
registerCreate(server);
registerStart(server);
registerStop(server);
registerRestart(server);
registerKill(server);
registerRm(server);
registerPause(server);
registerUnpause(server);
registerExec(server);
registerPull(server);
registerPush(server);
registerBuild(server);
registerTag(server);
registerRmi(server);
registerCommit(server);
registerSave(server);
registerLoad(server);
registerComposeUp(server);
registerComposeDown(server);
registerComposePs(server);
registerComposeLogs(server);
registerComposeBuild(server);
registerComposeRestart(server);
registerComposePull(server);
registerComposeExec(server);
registerVolumeCreate(server);
registerVolumeRm(server);
registerVolumeInspect(server);
registerVolumePrune(server);
registerNetworkCreate(server);
registerNetworkRm(server);
registerNetworkConnect(server);
registerNetworkDisconnect(server);
registerNetworkInspect(server);
registerNetworkPrune(server);
registerSystemPrune(server);
registerContainerPrune(server);
registerImagePrune(server);
registerCp(server);
registerStats(server);
registerTop(server);
registerEvents(server);
registerUpdate(server);
registerWait(server);
registerBuildxBuild(server);
registerBuildxLs(server);
registerBuildxCreate(server);
registerBuildxRm(server);
registerBuildxInspect(server);
registerBuildxUse(server);
registerBuildxImagetools(server);
registerBuilderPrune(server);
registerManifestCreate(server);
registerManifestInspect(server);
registerManifestAnnotate(server);
registerManifestPush(server);
registerManifestRm(server);
registerComposeConfig(server);
registerComposeCp(server);
registerComposeCreate(server);
registerComposeEvents(server);
registerComposeImages(server);
registerComposeKill(server);
registerComposeLs(server);
registerComposePause(server);
registerComposeUnpause(server);
registerComposePort(server);
registerComposeRm(server);
registerComposeRun(server);
registerComposeScale(server);
registerComposeStart(server);
registerComposeStop(server);
registerComposeTop(server);
registerDiff(server);
registerExport(server);
registerPort(server);
registerRename(server);
registerImageHistory(server);
registerImport(server);
registerContextCreate(server);
registerContextLs(server);
registerContextInspect(server);
registerContextRm(server);
registerContextUse(server);
registerContextShow(server);
registerLogin(server);
registerLogout(server);
registerSwarmInit(server);
registerSwarmJoin(server);
registerSwarmLeave(server);
registerSwarmJoinToken(server);
registerSwarmUpdate(server);
registerSwarmUnlock(server);
registerSwarmUnlockKey(server);
registerSwarmCa(server);
registerServiceCreate(server);
registerServiceUpdate(server);
registerServiceRm(server);
registerServiceLs(server);
registerServiceInspect(server);
registerServiceLogs(server);
registerServicePs(server);
registerServiceScale(server);
registerServiceRollback(server);
registerNodeLs(server);
registerNodeInspect(server);
registerNodePs(server);
registerNodeRm(server);
registerNodeUpdate(server);
registerNodePromote(server);
registerNodeDemote(server);
registerStackDeploy(server);
registerStackRm(server);
registerStackLs(server);
registerStackPs(server);
registerStackServices(server);
registerStackConfig(server);
registerConfigCreate(server);
registerConfigInspect(server);
registerConfigLs(server);
registerConfigRm(server);
registerSecretCreate(server);
registerSecretInspect(server);
registerSecretLs(server);
registerSecretRm(server);
registerTrustInspect(server);
registerTrustSign(server);
registerTrustRevoke(server);
registerTrustKey(server);
registerVersion(server);
registerComposeVersion(server);
registerComposeWatch(server);
registerScoutQuickview(server);
registerScoutCves(server);
registerScoutRecommendations(server);
registerPluginLs(server);
registerPluginInstall(server);
registerPluginRm(server);
registerPluginEnable(server);

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
