#!/usr/bin/env node

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

import { register as registerListContainers } from "./tools/listContainers.js";
import { register as registerInspectContainer } from "./tools/inspectContainer.js";
import { register as registerContainerLogs } from "./tools/containerLogs.js";
import { register as registerListImages } from "./tools/listImages.js";
import { register as registerInspectImage } from "./tools/inspectImage.js";
import { register as registerListVolumes } from "./tools/listVolumes.js";
import { register as registerListNetworks } from "./tools/listNetworks.js";
import { register as registerSystemInfo } from "./tools/systemInfo.js";
import { register as registerDiskUsage } from "./tools/diskUsage.js";
import { register as registerSearchHub } from "./tools/searchHub.js";
import { register as registerRun } from "./tools/run.js";
import { register as registerCreate } from "./tools/create.js";
import { register as registerStart } from "./tools/start.js";
import { register as registerStop } from "./tools/stop.js";
import { register as registerRestart } from "./tools/restart.js";
import { register as registerKill } from "./tools/kill.js";
import { register as registerRm } from "./tools/rm.js";
import { register as registerPause } from "./tools/pause.js";
import { register as registerUnpause } from "./tools/unpause.js";
import { register as registerExec } from "./tools/exec.js";
import { register as registerPull } from "./tools/pull.js";
import { register as registerPush } from "./tools/push.js";
import { register as registerBuild } from "./tools/build.js";
import { register as registerTag } from "./tools/tag.js";
import { register as registerRmi } from "./tools/rmi.js";
import { register as registerCommit } from "./tools/commit.js";
import { register as registerSave } from "./tools/save.js";
import { register as registerLoad } from "./tools/load.js";
import { register as registerComposeUp } from "./tools/composeUp.js";
import { register as registerComposeDown } from "./tools/composeDown.js";
import { register as registerComposePs } from "./tools/composePs.js";
import { register as registerComposeLogs } from "./tools/composeLogs.js";
import { register as registerComposeBuild } from "./tools/composeBuild.js";
import { register as registerComposeRestart } from "./tools/composeRestart.js";
import { register as registerComposePull } from "./tools/composePull.js";
import { register as registerComposeExec } from "./tools/composeExec.js";
import { register as registerVolumeCreate } from "./tools/volumeCreate.js";
import { register as registerVolumeRm } from "./tools/volumeRm.js";
import { register as registerVolumeInspect } from "./tools/volumeInspect.js";
import { register as registerVolumePrune } from "./tools/volumePrune.js";
import { register as registerNetworkCreate } from "./tools/networkCreate.js";
import { register as registerNetworkRm } from "./tools/networkRm.js";
import { register as registerNetworkConnect } from "./tools/networkConnect.js";
import { register as registerNetworkDisconnect } from "./tools/networkDisconnect.js";
import { register as registerNetworkInspect } from "./tools/networkInspect.js";
import { register as registerNetworkPrune } from "./tools/networkPrune.js";
import { register as registerSystemPrune } from "./tools/systemPrune.js";
import { register as registerContainerPrune } from "./tools/containerPrune.js";
import { register as registerImagePrune } from "./tools/imagePrune.js";
import { register as registerCp } from "./tools/cp.js";
import { register as registerStats } from "./tools/stats.js";
import { register as registerTop } from "./tools/top.js";
import { register as registerEvents } from "./tools/events.js";
import { register as registerUpdate } from "./tools/update.js";
import { register as registerWait } from "./tools/wait.js";
import { register as registerBuildxBuild } from "./tools/buildxBuild.js";
import { register as registerBuildxLs } from "./tools/buildxLs.js";
import { register as registerBuildxCreate } from "./tools/buildxCreate.js";
import { register as registerBuildxRm } from "./tools/buildxRm.js";
import { register as registerBuildxInspect } from "./tools/buildxInspect.js";
import { register as registerBuildxUse } from "./tools/buildxUse.js";
import { register as registerBuildxImagetools } from "./tools/buildxImagetools.js";
import { register as registerBuilderPrune } from "./tools/builderPrune.js";
import { register as registerManifestCreate } from "./tools/manifestCreate.js";
import { register as registerManifestInspect } from "./tools/manifestInspect.js";
import { register as registerManifestAnnotate } from "./tools/manifestAnnotate.js";
import { register as registerManifestPush } from "./tools/manifestPush.js";
import { register as registerManifestRm } from "./tools/manifestRm.js";
import { register as registerComposeConfig } from "./tools/composeConfig.js";
import { register as registerComposeCp } from "./tools/composeCp.js";
import { register as registerComposeCreate } from "./tools/composeCreate.js";
import { register as registerComposeEvents } from "./tools/composeEvents.js";
import { register as registerComposeImages } from "./tools/composeImages.js";
import { register as registerComposeKill } from "./tools/composeKill.js";
import { register as registerComposeLs } from "./tools/composeLs.js";
import { register as registerComposePause } from "./tools/composePause.js";
import { register as registerComposeUnpause } from "./tools/composeUnpause.js";
import { register as registerComposePort } from "./tools/composePort.js";
import { register as registerComposeRm } from "./tools/composeRm.js";
import { register as registerComposeRun } from "./tools/composeRun.js";
import { register as registerComposeScale } from "./tools/composeScale.js";
import { register as registerComposeStart } from "./tools/composeStart.js";
import { register as registerComposeStop } from "./tools/composeStop.js";
import { register as registerComposeTop } from "./tools/composeTop.js";
import { register as registerDiff } from "./tools/diff.js";
import { register as registerExport } from "./tools/export.js";
import { register as registerPort } from "./tools/port.js";
import { register as registerRename } from "./tools/rename.js";
import { register as registerImageHistory } from "./tools/imageHistory.js";
import { register as registerImport } from "./tools/import.js";
import { register as registerContextCreate } from "./tools/contextCreate.js";
import { register as registerContextLs } from "./tools/contextLs.js";
import { register as registerContextInspect } from "./tools/contextInspect.js";
import { register as registerContextRm } from "./tools/contextRm.js";
import { register as registerContextUse } from "./tools/contextUse.js";
import { register as registerContextShow } from "./tools/contextShow.js";
import { register as registerLogin } from "./tools/login.js";
import { register as registerLogout } from "./tools/logout.js";

const server = new McpServer({
  name: "docker-mcp",
  version: "0.9.0",
});

registerListContainers(server);
registerInspectContainer(server);
registerContainerLogs(server);
registerListImages(server);
registerInspectImage(server);
registerListVolumes(server);
registerListNetworks(server);
registerSystemInfo(server);
registerDiskUsage(server);
registerSearchHub(server);
registerRun(server);
registerCreate(server);
registerStart(server);
registerStop(server);
registerRestart(server);
registerKill(server);
registerRm(server);
registerPause(server);
registerUnpause(server);
registerExec(server);
registerPull(server);
registerPush(server);
registerBuild(server);
registerTag(server);
registerRmi(server);
registerCommit(server);
registerSave(server);
registerLoad(server);
registerComposeUp(server);
registerComposeDown(server);
registerComposePs(server);
registerComposeLogs(server);
registerComposeBuild(server);
registerComposeRestart(server);
registerComposePull(server);
registerComposeExec(server);
registerVolumeCreate(server);
registerVolumeRm(server);
registerVolumeInspect(server);
registerVolumePrune(server);
registerNetworkCreate(server);
registerNetworkRm(server);
registerNetworkConnect(server);
registerNetworkDisconnect(server);
registerNetworkInspect(server);
registerNetworkPrune(server);
registerSystemPrune(server);
registerContainerPrune(server);
registerImagePrune(server);
registerCp(server);
registerStats(server);
registerTop(server);
registerEvents(server);
registerUpdate(server);
registerWait(server);
registerBuildxBuild(server);
registerBuildxLs(server);
registerBuildxCreate(server);
registerBuildxRm(server);
registerBuildxInspect(server);
registerBuildxUse(server);
registerBuildxImagetools(server);
registerBuilderPrune(server);
registerManifestCreate(server);
registerManifestInspect(server);
registerManifestAnnotate(server);
registerManifestPush(server);
registerManifestRm(server);
registerComposeConfig(server);
registerComposeCp(server);
registerComposeCreate(server);
registerComposeEvents(server);
registerComposeImages(server);
registerComposeKill(server);
registerComposeLs(server);
registerComposePause(server);
registerComposeUnpause(server);
registerComposePort(server);
registerComposeRm(server);
registerComposeRun(server);
registerComposeScale(server);
registerComposeStart(server);
registerComposeStop(server);
registerComposeTop(server);
registerDiff(server);
registerExport(server);
registerPort(server);
registerRename(server);
registerImageHistory(server);
registerImport(server);
registerContextCreate(server);
registerContextLs(server);
registerContextInspect(server);
registerContextRm(server);
registerContextUse(server);
registerContextShow(server);
registerLogin(server);
registerLogout(server);

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
